defmodule AwsAsh.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sessions, primary_key: false) do
      add :client_id, :text, null: false
      add :in_port, :bigint, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:events, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "events_session_id_fkey", type: :uuid)

      add :json, :map, null: false
      add :service, :text, null: false
      add :client_id, :text, null: false
      add :api, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:events, "events_session_id_fkey")

    drop table(:events)

    drop table(:sessions)
  end
end
