defmodule AwsAsh.Repo.Migrations.AddEventType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :type, :text, null: false, default: ""
    end
  end

  def down do
    alter table(:events) do
      remove :type
    end
  end
end
